// 2027 season constants.
// Scaffolded by scripts/new-season.mjs from the 2026 season.
//
// TODO before opening day:
//   1. Roster — edit TEAMS below for any changes, then re-run the handicap
//      capture if pairings moved: npm run capture-hcp -- 2026
//   2. NEW_MEMBERS — flag anyone genuinely new (affects the handicap formula).
//   3. Tee-time accommodation — reorder each week's pairs so late-start teams
//      fall last; the order of the 9 pairs is the tee sheet.
//   4. Register in SEASONS and bump CURRENT_SEASON in constants/league.js.

const PAR         = [4,3,4,5,4,3,4,5,4];
const SI          = [1,3,7,8,4,9,2,6,5];
const RAINOUT_SUB = {6:0,7:3,8:2}; // H7→H1, H8→H4, H9→H3

// ── Teams ──────────────────────────────────────────────────────
// Carried forward from 2026. Edit for roster changes.
const TEAMS = {
  1:  {name:"Charles - Dagg",          p1:"Brian Charles",     p2:"Karl Dagg"},
  2:  {name:"Brosius - Albano",        p1:"Steve Brosius",     p2:"Mike Albano"},
  3:  {name:"Mistry - Reddy",          p1:"Baz Mistry",        p2:"Sanjay Reddy"},
  4:  {name:"Pineno - MacKenzie",      p1:"Scot Pineno",       p2:"Scott MacKenzie"},
  5:  {name:"Carickhoff - Schantz",    p1:"Jack Carickhoff",   p2:"Tracy Schantz"},
  6:  {name:"Glascott - Adler",        p1:"Scott Glascott",    p2:"Mark Adler"},
  7:  {name:"Harvey - Rowles",         p1:"John Harvey",       p2:"Jeff Rowles"},
  8:  {name:"Saenz - Huston",          p1:"Bob Saenz",         p2:"Dennis Huston"},
  9:  {name:"Fahey - Wzorek",          p1:"Chris Fahey",       p2:"Barry Wzorek"},
  10: {name:"Mulvey - Nelson",         p1:"Tom Mulvey",        p2:"Chris Nelson"},
  11: {name:"West - Herman",           p1:"Jack West",         p2:"Ron Herman"},
  12: {name:"Lorenz - Huckestein",     p1:"Gabe Lorenz",       p2:"Jake Huckestein"},
  13: {name:"Wagner - Hammond",        p1:"Betsy Wagner",      p2:"Gordon Hammond"},
  14: {name:"Franks - Lightbody",      p1:"John Franks",       p2:"Scott Lightbody"},
  15: {name:"Jurden - Olivos",         p1:"Jesse Jurden",      p2:"JC Olivos"},
  16: {name:"Lukas - Blizard",         p1:"Rhonda Lukas",      p2:"Carol Blizard"},
  17: {name:"Posey - Minasian",        p1:"Russ Posey",        p2:"Aret Minasian"},
  18: {name:"Pavelik - Mitchell",      p1:"Barry Pavelik",     p2:"Mark Mitchell"},
};

// Player list: {tid, pi, name}
const ALL_PLAYERS = Object.entries(TEAMS).flatMap(([tid,t]) => [
  {tid:parseInt(tid), pi:0, name:t.p1, team:t.name},
  {tid:parseInt(tid), pi:1, name:t.p2, team:t.name},
]);

// ── Schedule ───────────────────────────────────────────────────
// Generated by scripts/build-schedule.mjs (seed 2027). Single round-robin:
// 153 pairings, each exactly once. Weeks 18-21 are computed from seeds.
//
// NOTE: pair order within a week IS the tee sheet (getTeeTimes(week)[i] -> pairs[i]).
// Late-start accommodations are NOT applied — reorder weeks before opening day.
const SCHEDULE_RAW = [
  [1,  "2027-04-14", [1,12],[15,18],[9,14],[4,16],[2,7],[3,5],[6,11],[10,13],[8,17]],
  [2,  "2027-04-21", [1,15],[12,14],[16,18],[2,9],[3,4],[7,11],[5,13],[6,17],[8,10]],
  [3,  "2027-04-28", [1,14],[15,16],[2,12],[3,18],[9,11],[4,13],[7,17],[5,8],[6,10]],
  [4,  "2027-05-05", [1,16],[2,14],[3,15],[11,12],[13,18],[9,17],[4,8],[7,10],[5,6]],
  [5,  "2027-05-12", [1,2],[3,16],[11,14],[13,15],[12,17],[8,18],[9,10],[4,6],[5,7]],
  [6,  "2027-05-19", [1,3],[2,11],[13,16],[14,17],[8,15],[10,12],[6,18],[5,9],[4,7]],
  [7,  "2027-05-26", [1,11],[3,13],[2,17],[8,16],[10,14],[6,15],[5,12],[7,18],[4,9]],
  [8,  "2027-06-02", [1,13],[11,17],[3,8],[2,10],[6,16],[5,14],[7,15],[4,12],[9,18]],
  [9,  "2027-06-09", [1,17],[8,13],[10,11],[3,6],[2,5],[7,16],[4,14],[9,15],[12,18]],
  [10, "2027-06-16", [1,8],[10,17],[6,13],[5,11],[3,7],[2,4],[9,16],[14,18],[12,15]],
  [11, "2027-06-23", [1,10],[6,8],[5,17],[7,13],[4,11],[3,9],[2,18],[12,16],[14,15]],
  [12, "2027-06-30", [1,6],[5,10],[7,8],[4,17],[9,13],[11,18],[3,12],[2,15],[14,16]],
  [13, "2027-07-14", [1,5],[6,7],[4,10],[8,9],[17,18],[12,13],[11,15],[3,14],[2,16]],
  [14, "2027-07-21", [1,7],[4,5],[6,9],[10,18],[8,12],[15,17],[13,14],[11,16],[2,3]],
  [15, "2027-07-28", [1,4],[7,9],[5,18],[6,12],[10,15],[8,14],[16,17],[2,13],[3,11]],
  [16, "2027-08-04", [1,9],[4,18],[7,12],[5,15],[6,14],[10,16],[2,8],[3,17],[11,13]],
  [17, "2027-08-11", [1,18],[9,12],[4,15],[7,14],[5,16],[2,6],[3,10],[8,11],[13,17]],
  [18, "2027-08-18"],   // Knockdown: all 18 teams play — pairs computed from seeds
  [19, "2027-08-25"],   // Playoffs Quarterfinals: 1v8, 2v7, 3v6, 4v5
  [20, "2027-09-01"],   // Playoffs Semifinals
  [21, "2027-09-08"],   // Playoffs Finals
];

const BASE_TEE_TIMES = ["4:10 PM","4:20 PM","4:30 PM","4:40 PM","4:50 PM","5:00 PM","5:10 PM","5:20 PM","5:30 PM"];
const TEE_TIME_OVERRIDES = {};
function getTeeTimes(week) {
  return TEE_TIME_OVERRIDES[week] || BASE_TEE_TIMES;
}

function buildSchedule() {
  const s = {};
  for (const [week, date, ...pairs] of SCHEDULE_RAW) {
    s[week] = {week, date, pairs:(pairs||[]).filter(p=>Array.isArray(p))};
  }
  return s;
}
const SCHEDULE = buildSchedule();

// ── Starting handicaps ─────────────────────────────────────────
// Captured from 2026 through Week 18 (the Knockdown — the last week all 18
// teams play). Regenerate with: npm run capture-hcp -- 2026
const DEFAULT_HCP = {
  1:  [5,5],    // Brian Charles, Karl Dagg
  2:  [4,8],    // Steve Brosius, Mike Albano
  3:  [4,9],    // Baz Mistry, Sanjay Reddy
  4:  [7,8],    // Scot Pineno, Scott MacKenzie
  5:  [0,7],    // Jack Carickhoff, Tracy Schantz
  6:  [10,7],   // Scott Glascott, Mark Adler
  7:  [8,9],    // John Harvey, Jeff Rowles
  8:  [7,9],    // Bob Saenz, Dennis Huston
  9:  [6,10],   // Chris Fahey, Barry Wzorek
  10: [7,5],    // Tom Mulvey, Chris Nelson
  11: [8,14],   // Jack West, Ron Herman
  12: [15,1],   // Gabe Lorenz, Jake Huckestein
  13: [18,13],  // Betsy Wagner, Gordon Hammond
  14: [7,-1],   // John Franks, Scott Lightbody
  15: [12,12],  // Jesse Jurden, JC Olivos
  16: [8,26],   // Rhonda Lukas, Carol Blizard
  17: [10,11],  // Russ Posey, Aret Minasian
  18: [14,11],  // Barry Pavelik, Mark Mitchell
};

// ── New members — keyed by "tid-pi" ────────────────────────────
// TODO: a player flagged new in 2026 is no longer new unless they sat out.
const NEW_MEMBERS = {};

const HCP_PCT = [0, 0.90, 0.90, 0.90, 0.90];
const HCP_CAP = 2;
const HCP_ROUNDS = 7;
const NEW_MEMBER_HCP_PCT = 0.60;
const PLAYOFF_START_WEEK = 18;

export {
  PAR,
  SI,
  RAINOUT_SUB,
  TEAMS,
  ALL_PLAYERS,
  SCHEDULE_RAW,
  BASE_TEE_TIMES,
  TEE_TIME_OVERRIDES,
  getTeeTimes,
  buildSchedule,
  SCHEDULE,
  DEFAULT_HCP,
  NEW_MEMBERS,
  HCP_PCT,
  HCP_CAP,
  HCP_ROUNDS,
  NEW_MEMBER_HCP_PCT,
  PLAYOFF_START_WEEK,
};

export function isNewMember(tid, pi) {
  return !!NEW_MEMBERS[`${tid}-${pi}`];
}
